using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class MovableFurniturePart : MonoBehaviour
{
    public MovableFurniture parent;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void OnPointerClickDown()
    {
        parent.OnPointerClickDown();
    }

    public void OnPointerEnter()
    {
        parent.OnPointerEnter();
    }

    public void OnPointerExit()
    {
        parent.OnPointerExit();
    }
}
