using UnityEngine;

public class MovableFurniturePart : MonoBehaviour
{
    public MovableFurniture parent;
    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

    }

    public void OnPointerClickDown()
    {
        parent.OnPointerClickDown();
    }

    public void OnPointerEnter()
    {
        parent.OnPointerEnter();
    }

    public void OnPointerExit()
    {
        parent.OnPointerExit();
    }

    private void OnTriggerEnter(Collider other)
    {
        parent.OnFurnitureCollisionEnter(other);
    }

    private void OnTriggerExit(Collider other)
    {
        parent.OnFurnitureCollisionExit(other);
    }

    private void OnTriggerStay(Collider other)
    {
        parent.OnFurnitureCollisionStay(other);
    }
}
